from .file import File
from .user import User
from .vehicle import Vehicle
from .service import Service
from .customService import CustomService
from .location import Location
from .sparepart import SparePart
from .service_performed import ServicePerformed
from .service_performed_spare_part import ServicePerformedSparePart
from .preventive_maintenance import PreventiveMaintenance
from .fuel_refill import FuelRefill
from .tem_service_performed import TempServicePerformed
from .document import Document