from .file import File
from .user import User
from .vehicle import Vehicle
from .service import Service
from .customService import CustomService
from .location import Location
from .sparepart import SparePart
from .service_performed import ServicePerformed
from .servicioRealizado_Repuesto import ServicioRealizadoRepuesto